# Workspaces equivalentes a 1:term, 2:web, 3:music, 4:files y 5:system.
windowrule {
    name = terminales
    match:class = ^(foot|foot-term)$
    tag = terminal
}

windowrule {
    name = navegador
    match:class = ^(firefox)$
    tag = browser
}

windowrule {
    name = musica
    match:class = ^(foot-music|foot-music-ncmpcpp|foot-music-ncspot|foot-music-pyradio)$
    workspace = 3 silent
}

windowrule {
    name = archivos
    match:class = ^(foot-files)$
    workspace = 4 silent
}

windowrule {
    name = archivos-graficos
    match:class = ^(Thunar)$
    workspace = 4 silent
}

windowrule {
    name = sistema
    match:class = ^(foot-system)$
    workspace = 5 silent
}

# Menus auxiliares dentro de Foot.
windowrule {
    name = redes
    match:class = ^(impala-floating)$
    float = on
    center = on
}

windowrule {
    name = menus-flotantes
    match:class = ^(bluetui-floating|audio-floating|battery-floating)$
    float = on
    size = 760 430
    center = on
}
