general {
    hide_cursor = true
    grace = 2
}

background {
    monitor =
    path = ~/.config/hypr/wallpaper.png
    blur_passes = 2
    blur_size = 7
    color = rgb(1a1b26)
}

input-field {
    monitor =
    size = 420, 58
    outline_thickness = 2
    dots_size = 0.22
    dots_spacing = 0.28
    outer_color = rgb(a9b1d6)
    inner_color = rgba(1a1b26e6)
    font_color = rgb(a9b1d6)
    fade_on_empty = false
    placeholder_text = <span foreground="##787c99">Ingresá tu contraseña</span>
    fail_text = <span foreground="##f7768e">$FAIL</span>
    position = 0, -55
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    color = rgb(ffffff)
    font_size = 68
    font_family = JetBrainsMono Nerd Font
    position = 0, 90
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    color = rgb(7aa2f7)
    font_size = 16
    font_family = JetBrainsMono Nerd Font
    position = 0, 18
    halign = center
    valign = center
}
